### ISSUE TITLE
Services don't show up in Prisma cloud workspace

### ISSUE THREAD

**Issue by kverpoorten** [prisma/prisma-cloud-feedback#205]
Steps taken:

1. Add new heroku server with existing database
2. Rename created Heroku dyno to a decent, recognizable name
3. Removed heroku server from Prisma cloud; added new "existing server" to Prisma cloud which now points to the renamed heroku dyno
4. prisma init in CLI
5. prisma deploy in CLI

Result: all works perfectly fine as expected (although the server is labeled as "self-hosted" instead of "Heroku" in the dashboard)

Only annoying thing is the service is not showing up in Prisma cloud. It says there are no services on the server (but there are, and they work just fine).

**Comment by liamdanielduffy** [comment]
@marktani @divyenduz for additional context, posting screenshots here:

<img width="1081" alt="screen shot 2018-12-04 at 12 09 31 pm" src="https://user-images.githubusercontent.com/7659261/49423452-8e1dd700-f7bd-11e8-9031-949dbf96b287.png">
<img width="1110" alt="screen shot 2018-12-04 at 12 09 25 pm" src="https://user-images.githubusercontent.com/7659261/49423454-8fe79a80-f7bd-11e8-83d2-4bdd291176ba.png">

**Comment by lydiahallie** [comment]
Thanks for letting us know @liamdanielduffy @kverpoorten !

@kverpoorten, would it be possible to give me your workspace slug and the name of the server that isn't showing up? 🙂You can also send me a message on Slack with the information if you prefer that (to @ Lydia Hallie)

@liamdanielduffy  I looked into it, and it looks like the service `staging-prisma` has been deleted at some point. If this was unintentional, please let me know 🙂

**Comment by liamdanielduffy** [comment]
@lydiahallie thank you for your help!

Unfortunately, I don't think it was intentional. Even though the service no longer appears in the Prisma Cloud console, the service is still up and running on the same Heroku dyno that was created from the Prisma Cloud creation flow. It also responds without problems to queries & mutations sent to its endpoint. 

Is there any way to bring it back into visibility the Prisma Cloud console? 

Thanks again for helping me sort this out :)

**Comment by lydiahallie** [comment]
@liamdanielduffy no worries! Could you check if the service is visible for you now?

**Comment by liamdanielduffy** [comment]
@lydiahallie yes, it's back! Thanks so much!

**Comment by liamdanielduffy** [comment]
@lydiahallie unfortunately though, the service has a 'Not Healthy' status, and when clicked, does not load the console with the Data Browser and Playground link...

<img width="1060" alt="screen shot 2018-12-04 at 6 47 00 pm" src="https://user-images.githubusercontent.com/7659261/49444392-081d8280-f7f5-11e8-9d24-57503a754583.png">
 
The endpoint itself for the service still works. 

Is there any way to troubleshoot the connection between the working service on the Heroku server, and the service interface in Prisma Cloud?

**Comment by liamdanielduffy** [comment]
@lydiahallie I'm also seeing this in the logs from the Heroku dyno on which the `staging-prisma` server + service are deployed, even though the endpoint for the service still appears to be working

<img width="1440" alt="screen shot 2018-12-04 at 6 52 05 pm" src="https://user-images.githubusercontent.com/7659261/49444627-b9241d00-f7f5-11e8-9f60-1a12a27f84ee.png">

**Comment by kverpoorten** [comment]
> Thanks for letting us know @liamdanielduffy @kverpoorten !
> 
> @kverpoorten, would it be possible to give me your workspace slug and the name of the server that isn't showing up? 🙂You can also send me a message on Slack with the information if you prefer that (to @ Lydia Hallie)
> 
> @liamdanielduffy I looked into it, and it looks like the service `staging-prisma` has been deleted at some point. I will fix this 🙂

**Comment by kverpoorten** [comment]
> @kverpoorten, would it be possible to give me your workspace slug and the name of the server that isn't showing up? 🙂You can also send me a message on Slack with the information if you prefer that (to @ Lydia Hallie)

Hi,

I'm not sure anymore what I did, but I fixed it myself already... I think I just tried it again...

**Comment by liamdanielduffy** [comment]
@lydiahallie 

I tried to resolve this by deleting all services and servers, and starting from scratch.

After recreating servers in the Heroku flow for Prisma Cloud, I tried deploying servers there.

I ran `prisma deploy`, and after selecting my `staging-prisma` server, I ran into the error preventing me from deploying, which is described in [this issue](https://github.com/prisma/prisma/issues/2896#issue-348912796), with a `ERROR: Authentication token is invalid:...` error message. 

As suggested in [this comment](https://github.com/prisma/prisma/issues/2896#issuecomment-443664359) on that issue thread, I logged out and ran `prisma deploy -e .env`, with `PRISMA_MANAGEMENT_API_SECRET`, `PRISMA_SECRET`, and `PRISMA_ENDPOINT` in my `.env` file. 

The service then deployed successfully. However, it still doesn't show up in the Prisma Cloud console. 

I think this is because I deployed my service while logged out, so Prisma Cloud doesn't know that a service was added to my `staging-prisma` server. 

Is there a way that I can let Prisma Cloud know about the service I deployed, so it can recognize it?

If not, do you have any ideas about how I can resolve [this issue that prevents me from deploying when logged in](https://github.com/prisma/prisma/issues/2896#issue-348912796)?

**Comment by mikedklein** [comment]
So I found a weird workaround. I removed all items from my .env file (or used a new one passed in with the -e flag) Deployed to my Heroku server. And it worked. Then I went back in and added my PRISMA_SECRET and got the managementAPISecret from the Heroku box config vars and added that to the PRISMA_MANAGEMENT_API_SECRET. So far this has seemed to consistently work for me. That being said I noticed if I leave something related to secrets (Management or Prisma) in the env I will first get a token error. If I correct this by getting the vars off the Heroku server I then see no service and have to figure out how to delete it from the Heroku server manually.

**Comment by divyenduz** [comment]
This issue was resolved a couple of days ago. The issue was specific to Prisma Heroku servers. You would still need to run `Prisma deploy` once to make this work though. Please give it a go and feel free to close to issue if you think that it is indeed resolved. 

@mikedklein : Maybe the workaround just coincided with our fix and felt like a workaround while the generic issue is resolved? Can you please help me validate that? Thanks.

**Comment by mikedklein** [comment]
So as per the posts here and in Slack I believe this worked prior to the fix on your end. That being everything seems to be going much smoother and can verify setting up a new server then running a new deployment `prisma deploy -n` works as expected now and the service is visible.

**Comment by divyenduz** [comment]
@mikedklein : Thanks for the confirmation. 

@kverpoorten : I think that this is resolved for you as well? If yes, please feel free to close this issue :) 

And if anyone in this thread still has this issue, please let me know, I believe that the generic underlying issue is resolved.

**Comment by liamdanielduffy** [comment]
@divyenduz I am still unable to deploy and see the service.

Neither running `prisma deploy` nor `prisma deploy -e .env.staging` causes my service to appear in prisma cloud. (where `.env.staging` has my PRISMA_MANAGEMENT_API_SECRET and PRISMA_SECRET)

If there is a specific process to follow to fix this bug now, would you mind sharing what that is?

**Comment by liamdanielduffy** [comment]
@kverpoorten @divyenduz can this issue be re-opened? As I mentioned above, I believe I'm still having the same problem, and following the steps shared by @mikedklein hasn't helped.

**Comment by divyenduz** [comment]
@liamdanielduffy : Thanks for raising this again. 

Can you please reach out to `support@prisma.io`. I think this might be a specific issue rather than a generic one. If required, we would open a new issue after working on your specific use case.

**Comment by chanlito** [comment]
I don't think this is a specific issue, because services show up for prisma deploy on demo-server but not self-hosted ones.

**Comment by wuichen** [comment]
my services arent showing up either. i have deployed service from both local docker and heroku. however, neither of them are showing up on my services dashboard. only the demo ones do.

**Comment by chanlito** [comment]
@divyenduz can somebody on the Prisma team look into this?

**Comment by tomellwood-github** [comment]
Same thing is happening with me; I have a Heroku server and my service has deployed absolutely fine, everything works, it's just not showing up as a service in the Prisma console.

**Comment by ThariqS** [comment]
I'm also seeing this

**Comment by Atheane** [comment]
Same here (service deployed from heroku, prisma cli indicates the service is deployed, but no way to query with the playground because no valid token, even after a prisma token, and the service does not show up on prisma cloud dashboard). Thank you for your help !

**Comment by glitchbane** [comment]
I've been learning about GraphQL in general and Prisma in particular for the last week or so, for several hours a day.  I got to the deployment part and signed up for Prisma Cloud and have had nothing but trouble.   First, the servers didn't show as healthy.  I went away for 2 days and came back and suddenly they are healthy.  Now I click on one (either one) of my services and all I get is a spinner, and in the top bar the text "2 services running".  It would be helpful to know if this is actively being worked.

**Comment by msaspence** [comment]
For me the problem was that if I deployed locally (where I was logged into Prisma cloud with a `cloudSessionKey` value in `~/.prisma/config.yml`) services were added correctly. If however I deployed as part of a Heroku build where I was not logged in the service was not added to Prisma cloud. Which makes a lot of sense once you realise what is going on.

The solution was to take the `cloudSessionKey` value from `~/.prisma/config.yml` and put in the `PRISMA_CLOUD_SESSION_KEY` env variable for my Heroku apps and run `prisma login` before deployment. This ensured that services were correctly added to Prisma cloud.

I don't know if this is what other people are experiencing but if it is it seems to make sense to me, but I think the whole "Deploy as part of a Heroku build process" could do with some better documentation.
