### ISSUE TITLE
Metrics not working on Zeit Now deployment

### ISSUE THREAD

**Issue by jhalborg** [prisma/prisma-cloud-feedback#219]
Hey, 

I have my GraphQL app deployed on Zeit Now Serverless Docker (v2). It talks to my Prisma servers, which is hosted on their v1 cloud, scaled to a minimum of 1 instance at all times. The setup works fine, albeit a bit slow, which is why I after a user workshop yesterday was eager to inspect Apollo Engine for the app, as well as Prisma Metrics and my AWS RDS dashboard to see what causes around 1.5s p90 response times for most queries. However, no metrics were shown on Prisma:

![image](https://user-images.githubusercontent.com/6643672/46791469-830c7480-cd41-11e8-8766-06f212130ef9.png)

Nilan suggested in Slack that I create this bug report. 

The Prisma server that was live during the test was based on the `prismagraphql/prisma:1.15.3` image.

**Comment by marktani** [comment]
Metrics should work again, it was an issue in our metrics infrastructure that is now resolved.

**Comment by jhalborg** [comment]
Hey @marktani - Thanks a lot for fixing this so fast!

It seems some metrics work, at least - I now get a number for request count, but the rest is still blank, and I really need some stats for response times :-)

![image](https://user-images.githubusercontent.com/6643672/46958693-b4b37180-d09a-11e8-85e1-75be9e4a7194.png)

**Comment by jhalborg** [comment]
Scratch that, now DB usage in MB is also visible - but still missing response time 😅 

![image](https://user-images.githubusercontent.com/6643672/46958791-eaf0f100-d09a-11e8-811a-0352ddd32433.png)

**Comment by marktani** [comment]
Ok, please reach out to support@prisma.io and share your server endpoint so we can look into your server specifically 🙂

**Comment by frandiox** [comment]
All the metrics work for me again after updating to 1.19
